### ISSUE TITLE
From where to download LLaMA-v1 model?

### ISSUE THREAD

**Issue by inesriahi** [mlvlab/Flipped-VQA#4]
Hi!
Thank you for the great work!

It looks like this code is based on LLaMAv1 models. Although you provided the link to the original repository, I didn't get a reply when I applied to the form. Is there any other way to get the models' weights?

**Comment by ikodoh** [comment]
Thank you for your interest in our work.
I'm not sure I can provide LLaMAv1 weight due to the legal issue.
However, I found an unofficial LLaMAv1 7B weight at [huggingface](https://huggingface.co/nyanko7/LLaMA-7B/tree/main).
Also, to boost the performance, our model is compatible to LLaMAv2 but this needs for further hyperparameter tuning.

**Comment by fake-warrior8** [comment]
> Thank you for your interest in our work. I'm not sure I can provide LLaMAv1 weight due to the legal issue. However, I found an unofficial LLaMAv1 7B weight at [huggingface](https://huggingface.co/nyanko7/LLaMA-7B/tree/main). Also, you can try LLaMAv2 weight since our model is compatible to it, but it might require further hyperparameter tuning.

Have you compared the official LLaMAv1 7B weight to the weight of [huggingface](https://huggingface.co/nyanko7/LLaMA-7B/tree/main), are them the same?

**Comment by ikodoh** [comment]
Yes, they are exactly the same.
